import React from "react";
import IncomeByAgeGroupChart from "../components/IncomeByAgeGroupChart";
import Header from "../components/Header";
import { Box, Typography, Paper } from "@mui/material";

const IncomeByAgeGroupPage = () => {
  return (
    <Box height="100%" maxHeight="85vh" m="1.5rem 2.5rem">
      <Header
        title="INCOME BY AGE GROUP"
        subtitle="Analyze total income generated by different age groups"
      />
      <Paper
        sx={{ padding: "16px", marginTop: "20px", marginBottom: "20px" }}
        elevation={3}
      >
        <Typography variant="h8">
          This chart provides insights into the total income generated by
          customers in each age group. It helps identify high-earning age
          segments, enabling businesses to target lucrative demographics
          effectively.
        </Typography>
      </Paper>
      <Box mt="40px" height="72vh">
        <IncomeByAgeGroupChart />
      </Box>
    </Box>
  );
};

export default IncomeByAgeGroupPage;
